/* Generated By:JJTree: Do not edit this line. ASTArrayLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package FESI.AST;

import FESI.Parser.*;

public
class ASTArrayLiteral extends SimpleNode {
    private static final long serialVersionUID = 7125731910996821294L;

    public ASTArrayLiteral(int id) {
        super(id);
    }

    public ASTArrayLiteral(EcmaScript p, int id) {
        super(p, id);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=ca27e417d2278fd01ec70dc7f1d02eb1 (do not edit this line) */
