/* Generated By:JJTree: Do not edit this line. ASTCatch.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package FESI.AST;

import FESI.Parser.*;

public
class ASTCatch extends SimpleNode {
    private static final long serialVersionUID = 4490222771647222225L;
    private Object evaluationSource;

    public ASTCatch(int id) {
        super(id);
    }

    public ASTCatch(EcmaScript p, int id) {
        super(p, id);
    }


    /** Accept the visitor. **/
    @Override
    public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public void setEvaluationSource(Object evaluationSource) {
        this.evaluationSource = evaluationSource;
    }

    public Object getEvaluationSource() {
        return evaluationSource;
    }
}
/* JavaCC - OriginalChecksum=42992cd1649f896a7e2e68e376aac12b (do not edit this line) */
