/* Generated By:JJTree: Do not edit this line. ASTDefaultClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package FESI.AST;

import FESI.Parser.*;

public
class ASTDefaultClause extends SimpleNode {
    private static final long serialVersionUID = 1L;


    public ASTDefaultClause(int id) {
        super(id);
    }

    public ASTDefaultClause(EcmaScript p, int id) {
        super(p, id);
    }


    /** Accept the visitor. **/
    @Override
    public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=f25777b8baf1d3e03fcb103c92f77c23 (do not edit this line) */
