/* Generated By:JJTree: Do not edit this line. ASTElision.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package FESI.AST;

import FESI.Parser.*;

public class ASTElision extends SimpleNode {
    private static final long serialVersionUID = -6461328857222384134L;

    public ASTElision(int id) {
        super(id);
    }

    public ASTElision(EcmaScript p, int id) {
        super(p, id);
    }

    /** Accept the visitor. **/
    @Override
    public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
/*
 * JavaCC - OriginalChecksum=9fbc9003e5410b4c2c1c05f3b694d67a (do not edit this
 * line)
 */
