/* Generated By:JJTree: Do not edit this line. ASTFunctionExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package FESI.AST;

import FESI.Parser.*;

public
class ASTFunctionExpression extends SimpleNode {
  private static final long serialVersionUID = -6085961813205509357L;

  public ASTFunctionExpression(int id) {
    super(id);
  }

  public ASTFunctionExpression(EcmaScript p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  @Override
public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

public void setSourceString(String string) {
    // TODO Auto-generated method stub
    
}
}
/* JavaCC - OriginalChecksum=77120c9529c0e1298867f0fd9900eca7 (do not edit this line) */
