/* Generated By:JJTree: Do not edit this line. ASTForStatement.java */

package FESI.AST;

import FESI.Parser.EcmaScript;

public class ASTForStatement extends SimpleNode {
    /**
	 * 
	 */
    private static final long serialVersionUID = -642453135512673236L;

    public ASTForStatement(int id) {
        super(id);
    }

    public ASTForStatement(EcmaScript p, int id) {
        super(p, id);
    }

    public static Node jjtCreate(int id) {
        return new ASTForStatement(id);
    }

    public static Node jjtCreate(EcmaScript p, int id) {
        return new ASTForStatement(p, id);
    }

    /** Accept the visitor. **/
    @Override
    public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}