/* Generated By:JJTree: Do not edit this line. ASTGetAccessor.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package FESI.AST;

import FESI.Parser.*;

public class ASTGetAccessor extends SimpleNode {
    private static final long serialVersionUID = 258294459179974363L;

    public ASTGetAccessor(int id) {
        super(id);
    }

    public ASTGetAccessor(EcmaScript p, int id) {
        super(p, id);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
/*
 * JavaCC - OriginalChecksum=3d6998df7353f9b416346775cb34080e (do not edit this
 * line)
 */
