/* Generated By:JJTree: Do not edit this line. ASTIdentifier.java */

package FESI.AST;

import FESI.Data.ESString;
import FESI.Parser.EcmaScript;
import FESI.Parser.ParseException;

public class ASTIdentifier extends SimpleNode {
    private static final long serialVersionUID = 2673088409445831343L;
    private ESString identifierName = null;
    private int hash = 0;

    public ASTIdentifier(int id) {
        super(id);
    }

    public ASTIdentifier(EcmaScript p, int id) {
        super(p, id);
    }

    public static Node jjtCreate(int id) {
        return new ASTIdentifier(id);
    }

    public static Node jjtCreate(EcmaScript p, int id) {
        return new ASTIdentifier(p, id);
    }

    /** Accept the visitor. **/
    @Override
    public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    // JMCL
    public void setName(String identifierName) throws ParseException {
        int len = identifierName.length();
        StringBuilder sb = new StringBuilder(len);

        // Unicode escape processing
        parent: 
            for (int i = 0; i < len; i++) {
            char c = identifierName.charAt(i);
            if (c == '\\') {
                if (identifierName.charAt(++i) == 'u' && (i + 4) < len) {
                    c = 0;
                    for (int j = 1; j < 5; j++) {
                        char c1 = identifierName.charAt(i + j);
                        if (isHex(c1)) {
                            c = (char) ((c << 4) | hexval(c1));
                        } else {
                            sb.append('u');
                            continue parent;
                        }
                    }
                    i += 4;
                }
            }
            
            sb.append(c);
        }

        identifierName = sb.toString();
        this.identifierName = new ESString(identifierName);
        this.hash = identifierName.hashCode();
    }

    @Override
    public int hashCode() {
        return hash;
    }

    public String getName() {
        return identifierName.toString();
    }

    public ESString getESName() {
        return identifierName;
    }

    @Override
    public String toString() {
        return "<" + identifierName + ">";
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj instanceof ASTIdentifier) {
            ASTIdentifier other = (ASTIdentifier) obj;
            return this.identifierName.equals(other.identifierName);
        }
        return false;
    }
}
