/* Generated By:JJTree: Do not edit this line. ASTObjectLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package FESI.AST;

import FESI.Parser.*;

public
class ASTObjectLiteral extends SimpleNode {
  private static final long serialVersionUID = 6672782721840221538L;


  public ASTObjectLiteral(int id) {
    super(id);
  }

  public ASTObjectLiteral(EcmaScript p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b0a0af6cf6f0280cb647808d611661e9 (do not edit this line) */
