/* Generated By:JJTree: Do not edit this line. ASTPropertyNameAndValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package FESI.AST;

import FESI.Parser.*;

public
class ASTPropertyNameAndValue extends SimpleNode {
  private static final long serialVersionUID = -1180346295350524408L;


  public ASTPropertyNameAndValue(int id) {
    super(id);
  }

  public ASTPropertyNameAndValue(EcmaScript p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  @Override
public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7c113d6ab024af49d97f9d08e7a28623 (do not edit this line) */
