/* Generated By:JJTree: Do not edit this line. ASTRegexp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package FESI.AST;

import FESI.Parser.EcmaScript;

public class ASTRegexp extends SimpleNode {
    private static final long serialVersionUID = -4544561313784938405L;
    private String body;
    private String flags;

    public ASTRegexp(int id) {
        super(id);
    }

    public ASTRegexp(EcmaScript p, int id) {
        super(p, id);
    }


    /** Accept the visitor. **/
    public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public void setRegularExpression(String image) {
        int lastIndex = image.lastIndexOf('/');
        body = image.substring(1, lastIndex);
        flags = image.substring(lastIndex+1);
    }

    @Override
    public String toString() {
        return "/"+body+"/"+flags;
    }

    public String getBody() {
        return body;
    }
    
    public String getFlags() {
        return flags;
    }
}
/* JavaCC - OriginalChecksum=a54a296cd31b042769b66445ea5a2527 (do not edit this line) */
