/* Generated By:JJTree: Do not edit this line. ASTTryStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package FESI.AST;

import FESI.Parser.*;

public
class ASTTryStatement extends SimpleNode {
  private static final long serialVersionUID = -1120411358916420260L;


  public ASTTryStatement(int id) {
    super(id);
  }

  public ASTTryStatement(EcmaScript p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=80f211112fe1ff86caa5628c732b567e (do not edit this line) */
