/* Generated By:JavaCC: Do not edit this line. EcmaScriptTreeConstants.java Version 5.0 */
package FESI.AST;

public interface EcmaScriptTreeConstants {
    public int JJTLITERAL = 0;
    public int JJTIDENTIFIER = 1;
    public int JJTVOID = 2;
    public int JJTTHISREFERENCE = 3;
    public int JJTSUPERREFERENCE = 4;
    public int JJTCOMPOSITEREFERENCE = 5;
    public int JJTFUNCTIONCALLPARAMETERS = 6;
    public int JJTPROPERTYVALUEREFERENCE = 7;
    public int JJTPROPERTYIDENTIFIERREFERENCE = 8;
    public int JJTALLOCATIONEXPRESSION = 9;
    public int JJTOPERATOR = 10;
    public int JJTPOSTFIXEXPRESSION = 11;
    public int JJTUNARYEXPRESSION = 12;
    public int JJTBINARYEXPRESSIONSEQUENCE = 13;
    public int JJTANDEXPRESSIONSEQUENCE = 14;
    public int JJTOREXPRESSIONSEQUENCE = 15;
    public int JJTCONDITIONALEXPRESSION = 16;
    public int JJTASSIGNMENTEXPRESSION = 17;
    public int JJTEXPRESSIONLIST = 18;
    public int JJTSTATEMENT = 19;
    public int JJTSTATEMENTLIST = 20;
    public int JJTVARIABLEDECLARATION = 21;
    public int JJTIFSTATEMENT = 22;
    public int JJTWHILESTATEMENT = 23;
    public int JJTFORSTATEMENT = 24;
    public int JJTEMPTYEXPRESSION = 25;
    public int JJTFORVARSTATEMENT = 26;
    public int JJTFORINSTATEMENT = 27;
    public int JJTFORVARINSTATEMENT = 28;
    public int JJTCONTINUESTATEMENT = 29;
    public int JJTBREAKSTATEMENT = 30;
    public int JJTRETURNSTATEMENT = 31;
    public int JJTWITHSTATEMENT = 32;
    public int JJTFUNCTIONDECLARATION = 33;
    public int JJTFORMALPARAMETERLIST = 34;
    public int JJTPROGRAM = 35;

    public String[] jjtNodeName = { "Literal", "Identifier", "void",
            "ThisReference", "SuperReference", "CompositeReference",
            "FunctionCallParameters", "PropertyValueReference",
            "PropertyIdentifierReference", "AllocationExpression", "Operator",
            "PostfixExpression", "UnaryExpression", "BinaryExpressionSequence",
            "AndExpressionSequence", "OrExpressionSequence",
            "ConditionalExpression", "AssignmentExpression", "ExpressionList",
            "Statement", "StatementList", "VariableDeclaration", "IfStatement",
            "WhileStatement", "ForStatement", "EmptyExpression",
            "ForVarStatement", "ForInStatement", "ForVarInStatement",
            "ContinueStatement", "BreakStatement", "ReturnStatement",
            "WithStatement", "FunctionDeclaration", "FormalParameterList",
            "Program", };
}
/*
 * JavaCC - OriginalChecksum=51bea45ba33c9c5a7968eb701d24eb2d (do not edit this
 * line)
 */
