/* Generated By:JavaCC: Do not edit this line. EcmaScriptTreeConstants.java Version 5.0 */
package FESI.AST;


public interface EcmaScriptTreeConstants
{
  public int JJTLITERAL = 0;
  public int JJTREGEXP = 1;
  public int JJTVOID = 2;
  public int JJTIDENTIFIER = 3;
  public int JJTCOMPOSITEREFERENCE = 4;
  public int JJTTHISREFERENCE = 5;
  public int JJTSUPERREFERENCE = 6;
  public int JJTFUNCTIONEXPRESSION = 7;
  public int JJTFORMALPARAMETERLIST = 8;
  public int JJTFUNCTIONCALLPARAMETERS = 9;
  public int JJTPROPERTYVALUEREFERENCE = 10;
  public int JJTPROPERTYIDENTIFIERREFERENCE = 11;
  public int JJTALLOCATIONEXPRESSION = 12;
  public int JJTARRAYLITERAL = 13;
  public int JJTELISION = 14;
  public int JJTOBJECTLITERAL = 15;
  public int JJTPROPERTYNAMEANDVALUE = 16;
  public int JJTGETACCESSOR = 17;
  public int JJTSETACCESSOR = 18;
  public int JJTOPERATOR = 19;
  public int JJTPOSTFIXEXPRESSION = 20;
  public int JJTUNARYEXPRESSION = 21;
  public int JJTBINARYEXPRESSIONSEQUENCE = 22;
  public int JJTANDEXPRESSIONSEQUENCE = 23;
  public int JJTOREXPRESSIONSEQUENCE = 24;
  public int JJTCONDITIONALEXPRESSION = 25;
  public int JJTASSIGNMENTEXPRESSION = 26;
  public int JJTEXPRESSIONLIST = 27;
  public int JJTSTATEMENT = 28;
  public int JJTSTATEMENTLIST = 29;
  public int JJTVARIABLEDECLARATION = 30;
  public int JJTIFSTATEMENT = 31;
  public int JJTDOWHILESTATEMENT = 32;
  public int JJTWHILESTATEMENT = 33;
  public int JJTFORSTATEMENT = 34;
  public int JJTEMPTYEXPRESSION = 35;
  public int JJTFORVARSTATEMENT = 36;
  public int JJTFORINSTATEMENT = 37;
  public int JJTFORVARINSTATEMENT = 38;
  public int JJTCONTINUESTATEMENT = 39;
  public int JJTBREAKSTATEMENT = 40;
  public int JJTRETURNSTATEMENT = 41;
  public int JJTWITHSTATEMENT = 42;
  public int JJTTRYSTATEMENT = 43;
  public int JJTTHROWSTATEMENT = 44;
  public int JJTCATCH = 45;
  public int JJTFINALLY = 46;
  public int JJTSWITCHSTATEMENT = 47;
  public int JJTCASECLAUSE = 48;
  public int JJTDEFAULTCLAUSE = 49;
  public int JJTFUNCTIONDECLARATION = 50;
  public int JJTPROGRAM = 51;


  public String[] jjtNodeName = {
    "Literal",
    "Regexp",
    "void",
    "Identifier",
    "CompositeReference",
    "ThisReference",
    "SuperReference",
    "FunctionExpression",
    "FormalParameterList",
    "FunctionCallParameters",
    "PropertyValueReference",
    "PropertyIdentifierReference",
    "AllocationExpression",
    "ArrayLiteral",
    "Elision",
    "ObjectLiteral",
    "PropertyNameAndValue",
    "GetAccessor",
    "SetAccessor",
    "Operator",
    "PostfixExpression",
    "UnaryExpression",
    "BinaryExpressionSequence",
    "AndExpressionSequence",
    "OrExpressionSequence",
    "ConditionalExpression",
    "AssignmentExpression",
    "ExpressionList",
    "Statement",
    "StatementList",
    "VariableDeclaration",
    "IfStatement",
    "DoWhileStatement",
    "WhileStatement",
    "ForStatement",
    "EmptyExpression",
    "ForVarStatement",
    "ForInStatement",
    "ForVarInStatement",
    "ContinueStatement",
    "BreakStatement",
    "ReturnStatement",
    "WithStatement",
    "TryStatement",
    "ThrowStatement",
    "Catch",
    "Finally",
    "SwitchStatement",
    "CaseClause",
    "DefaultClause",
    "FunctionDeclaration",
    "Program",
  };
}
/* JavaCC - OriginalChecksum=ed0092f18e02b061008d92fdc1f253e2 (do not edit this line) */
