/* Generated By:JJTree&JavaCC: Do not edit this line. EcmaScriptConstants.java */
// $codepro.audit.disable
package FESI.Parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EcmaScriptConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TAB = 1;
  /** RegularExpression Id. */
  int VT = 2;
  /** RegularExpression Id. */
  int FF = 3;
  /** RegularExpression Id. */
  int SP = 4;
  /** RegularExpression Id. */
  int NBSP = 5;
  /** RegularExpression Id. */
  int BOM = 6;
  /** RegularExpression Id. */
  int USP = 7;
  /** RegularExpression Id. */
  int LF = 8;
  /** RegularExpression Id. */
  int CR = 9;
  /** RegularExpression Id. */
  int LS = 10;
  /** RegularExpression Id. */
  int PS = 11;
  /** RegularExpression Id. */
  int EOL = 12;
  /** RegularExpression Id. */
  int NO_SKIP_EOL = 13;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 14;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 16;
  /** RegularExpression Id. */
  int BREAK = 18;
  /** RegularExpression Id. */
  int CONTINUE = 19;
  /** RegularExpression Id. */
  int DELETE = 20;
  /** RegularExpression Id. */
  int ELSE = 21;
  /** RegularExpression Id. */
  int FOR = 22;
  /** RegularExpression Id. */
  int FUNCTION = 23;
  /** RegularExpression Id. */
  int IF = 24;
  /** RegularExpression Id. */
  int IN = 25;
  /** RegularExpression Id. */
  int NEW = 26;
  /** RegularExpression Id. */
  int RETURN = 27;
  /** RegularExpression Id. */
  int THIS = 28;
  /** RegularExpression Id. */
  int TYPEOF = 29;
  /** RegularExpression Id. */
  int VAR = 30;
  /** RegularExpression Id. */
  int VOID = 31;
  /** RegularExpression Id. */
  int WHILE = 32;
  /** RegularExpression Id. */
  int WITH = 33;
  /** RegularExpression Id. */
  int CASE = 34;
  /** RegularExpression Id. */
  int CATCH = 35;
  /** RegularExpression Id. */
  int CLASS = 36;
  /** RegularExpression Id. */
  int CONST = 37;
  /** RegularExpression Id. */
  int DEBUGGER = 38;
  /** RegularExpression Id. */
  int _DEFAULT = 39;
  /** RegularExpression Id. */
  int DO = 40;
  /** RegularExpression Id. */
  int ENUM = 41;
  /** RegularExpression Id. */
  int EXPORT = 42;
  /** RegularExpression Id. */
  int EXTENDS = 43;
  /** RegularExpression Id. */
  int FINALLY = 44;
  /** RegularExpression Id. */
  int IMPORT = 45;
  /** RegularExpression Id. */
  int SUPER = 46;
  /** RegularExpression Id. */
  int SWITCH = 47;
  /** RegularExpression Id. */
  int THROW = 48;
  /** RegularExpression Id. */
  int TRY = 49;
  /** RegularExpression Id. */
  int INSTANCEOF = 50;
  /** RegularExpression Id. */
  int TRUE = 51;
  /** RegularExpression Id. */
  int FALSE = 52;
  /** RegularExpression Id. */
  int NULL = 53;
  /** RegularExpression Id. */
  int GET = 54;
  /** RegularExpression Id. */
  int SET = 55;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 56;
  /** RegularExpression Id. */
  int HEX_LITERAL = 57;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 58;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 59;
  /** RegularExpression Id. */
  int EXPONENT = 60;
  /** RegularExpression Id. */
  int STRING_LITERAL = 61;
  /** RegularExpression Id. */
  int SINGLE_STRING_LITERAL_BODY = 62;
  /** RegularExpression Id. */
  int DOUBLE_STRING_LITERAL_BODY = 63;
  /** RegularExpression Id. */
  int UNTERMINATED_STRING_LITERAL = 64;
  /** RegularExpression Id. */
  int REGULAR_EXPRESSION_LITERAL = 65;
  /** RegularExpression Id. */
  int REGULAR_EXPRESSION_BODY = 66;
  /** RegularExpression Id. */
  int REGULAR_EXPRESSION_CHAR = 67;
  /** RegularExpression Id. */
  int REGULAR_EXPRESSION_FIRST_CHAR = 68;
  /** RegularExpression Id. */
  int REGULAR_EXPRESSION_BACKSLASH_SEQUENCE = 69;
  /** RegularExpression Id. */
  int REGULAR_EXPRESSION_CLASS = 70;
  /** RegularExpression Id. */
  int REGULAR_EXPRESSION_CLASS_CHAR = 71;
  /** RegularExpression Id. */
  int IDENTIFIER = 72;
  /** RegularExpression Id. */
  int IDENTIFIER_START = 73;
  /** RegularExpression Id. */
  int IDENTIFIER_PART = 74;
  /** RegularExpression Id. */
  int UNICODE_LETTER = 75;
  /** RegularExpression Id. */
  int UNICODE_ESCAPE_SEQUENCE = 76;
  /** RegularExpression Id. */
  int UNICODE_COMBINING_MARK = 77;
  /** RegularExpression Id. */
  int UNICODE_DIGIT = 78;
  /** RegularExpression Id. */
  int UNICODE_CONNECTOR_PUNCTUATION = 79;
  /** RegularExpression Id. */
  int ZWNJ = 80;
  /** RegularExpression Id. */
  int ZWJ = 81;
  /** RegularExpression Id. */
  int HEX_DIGIT = 82;
  /** RegularExpression Id. */
  int LPAREN = 83;
  /** RegularExpression Id. */
  int RPAREN = 84;
  /** RegularExpression Id. */
  int LBRACE = 85;
  /** RegularExpression Id. */
  int RBRACE = 86;
  /** RegularExpression Id. */
  int LBRACKET = 87;
  /** RegularExpression Id. */
  int RBRACKET = 88;
  /** RegularExpression Id. */
  int SEMICOLON = 89;
  /** RegularExpression Id. */
  int COMMA = 90;
  /** RegularExpression Id. */
  int DOT = 91;
  /** RegularExpression Id. */
  int ASSIGN = 92;
  /** RegularExpression Id. */
  int GT = 93;
  /** RegularExpression Id. */
  int LT = 94;
  /** RegularExpression Id. */
  int BANG = 95;
  /** RegularExpression Id. */
  int TILDE = 96;
  /** RegularExpression Id. */
  int HOOK = 97;
  /** RegularExpression Id. */
  int COLON = 98;
  /** RegularExpression Id. */
  int STRICT_EQ = 99;
  /** RegularExpression Id. */
  int STRICT_NEQ = 100;
  /** RegularExpression Id. */
  int EQ = 101;
  /** RegularExpression Id. */
  int LE = 102;
  /** RegularExpression Id. */
  int GE = 103;
  /** RegularExpression Id. */
  int NE = 104;
  /** RegularExpression Id. */
  int SC_OR = 105;
  /** RegularExpression Id. */
  int SC_AND = 106;
  /** RegularExpression Id. */
  int INCR = 107;
  /** RegularExpression Id. */
  int NL_INCR = 108;
  /** RegularExpression Id. */
  int DECR = 109;
  /** RegularExpression Id. */
  int NL_DECR = 110;
  /** RegularExpression Id. */
  int PLUS = 111;
  /** RegularExpression Id. */
  int MINUS = 112;
  /** RegularExpression Id. */
  int STAR = 113;
  /** RegularExpression Id. */
  int SLASH = 114;
  /** RegularExpression Id. */
  int BIT_AND = 115;
  /** RegularExpression Id. */
  int BIT_OR = 116;
  /** RegularExpression Id. */
  int XOR = 117;
  /** RegularExpression Id. */
  int REM = 118;
  /** RegularExpression Id. */
  int LSHIFT = 119;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 120;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 121;
  /** RegularExpression Id. */
  int PLUSASSIGN = 122;
  /** RegularExpression Id. */
  int MINUSASSIGN = 123;
  /** RegularExpression Id. */
  int STARASSIGN = 124;
  /** RegularExpression Id. */
  int SLASHASSIGN = 125;
  /** RegularExpression Id. */
  int ANDASSIGN = 126;
  /** RegularExpression Id. */
  int ORASSIGN = 127;
  /** RegularExpression Id. */
  int XORASSIGN = 128;
  /** RegularExpression Id. */
  int REMASSIGN = 129;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 130;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 131;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 132;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int NOREGEXP = 1;
  /** Lexical state. */
  int NOEOL = 2;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\u000b\"",
    "\"\\f\"",
    "\" \"",
    "\"\\u00a0\"",
    "\"\\ufeff\"",
    "<USP>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\u2028\"",
    "\"\\u2029\"",
    "<EOL>",
    "<NO_SKIP_EOL>",
    "<SINGLE_LINE_COMMENT>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 17>",
    "\"break\"",
    "\"continue\"",
    "\"delete\"",
    "\"else\"",
    "\"for\"",
    "\"function\"",
    "\"if\"",
    "\"in\"",
    "\"new\"",
    "\"return\"",
    "\"this\"",
    "\"typeof\"",
    "\"var\"",
    "\"void\"",
    "\"while\"",
    "\"with\"",
    "\"case\"",
    "\"catch\"",
    "\"class\"",
    "\"const\"",
    "\"debugger\"",
    "\"default\"",
    "\"do\"",
    "\"enum\"",
    "\"export\"",
    "\"extends\"",
    "\"finally\"",
    "\"import\"",
    "\"super\"",
    "\"switch\"",
    "\"throw\"",
    "\"try\"",
    "\"instanceof\"",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\"get\"",
    "\"set\"",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "<SINGLE_STRING_LITERAL_BODY>",
    "<DOUBLE_STRING_LITERAL_BODY>",
    "<UNTERMINATED_STRING_LITERAL>",
    "<REGULAR_EXPRESSION_LITERAL>",
    "<REGULAR_EXPRESSION_BODY>",
    "<REGULAR_EXPRESSION_CHAR>",
    "<REGULAR_EXPRESSION_FIRST_CHAR>",
    "<REGULAR_EXPRESSION_BACKSLASH_SEQUENCE>",
    "<REGULAR_EXPRESSION_CLASS>",
    "<REGULAR_EXPRESSION_CLASS_CHAR>",
    "<IDENTIFIER>",
    "<IDENTIFIER_START>",
    "<IDENTIFIER_PART>",
    "<UNICODE_LETTER>",
    "<UNICODE_ESCAPE_SEQUENCE>",
    "<UNICODE_COMBINING_MARK>",
    "<UNICODE_DIGIT>",
    "<UNICODE_CONNECTOR_PUNCTUATION>",
    "\"\\u200d\"",
    "\"\\u200c\"",
    "<HEX_DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"===\"",
    "\"!==\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "<NL_INCR>",
    "\"--\"",
    "<NL_DECR>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
  };

}
