/* Generated By:JJTree: Do not edit this line. ASTConditionalExpression.java */

package FESI.AST;

import FESI.Parser.EcmaScript;

public class ASTConditionalExpression extends SimpleNode {
    /**
	 * 
	 */
    private static final long serialVersionUID = -3570744060575164301L;

    public ASTConditionalExpression(int id) {
        super(id);
    }

    public ASTConditionalExpression(EcmaScript p, int id) {
        super(p, id);
    }

    public static Node jjtCreate(int id) {
        return new ASTConditionalExpression(id);
    }

    public static Node jjtCreate(EcmaScript p, int id) {
        return new ASTConditionalExpression(p, id);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}