/* Generated By:JJTree: Do not edit this line. ASTDoWhileStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package FESI.AST;

import FESI.Parser.*;

public
class ASTDoWhileStatement extends SimpleNode {
  private static final long serialVersionUID = 3176918497358512763L;


  public ASTDoWhileStatement(int id) {
    super(id);
  }

  public ASTDoWhileStatement(EcmaScript p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=43fc094349b08b57c342d10da214e01b (do not edit this line) */
