/* Generated By:JJTree: Do not edit this line. ASTExpressionList.java */

package FESI.AST;

import FESI.Parser.EcmaScript;

public class ASTExpressionList extends SimpleNode {
    /**
	 * 
	 */
    private static final long serialVersionUID = 1990821163131190382L;

    public ASTExpressionList(int id) {
        super(id);
    }

    public ASTExpressionList(EcmaScript p, int id) {
        super(p, id);
    }

    public static Node jjtCreate(int id) {
        return new ASTExpressionList(id);
    }

    public static Node jjtCreate(EcmaScript p, int id) {
        return new ASTExpressionList(p, id);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}