/* Generated By:JJTree: Do not edit this line. ASTForInStatement.java */

package FESI.AST;

import FESI.Parser.EcmaScript;

public class ASTForInStatement extends SimpleNode {
    /**
	 * 
	 */
    private static final long serialVersionUID = -3100645383649230433L;

    public ASTForInStatement(int id) {
        super(id);
    }

    public ASTForInStatement(EcmaScript p, int id) {
        super(p, id);
    }

    public static Node jjtCreate(int id) {
        return new ASTForInStatement(id);
    }

    public static Node jjtCreate(EcmaScript p, int id) {
        return new ASTForInStatement(p, id);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}