/* Generated By:JJTree: Do not edit this line. ASTSetAccessor.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package FESI.AST;

import FESI.Parser.*;

public class ASTSetAccessor extends SimpleNode {
    private static final long serialVersionUID = -5120275019632560136L;

    public ASTSetAccessor(int id) {
        super(id);
    }

    public ASTSetAccessor(EcmaScript p, int id) {
        super(p, id);
    }

    /** Accept the visitor. **/
    @Override
    public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
/*
 * JavaCC - OriginalChecksum=f0806701f87451bf6cb31909b6cb0113 (do not edit this
 * line)
 */
