/* Generated By:JJTree: Do not edit this line. ASTSwitchStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package FESI.AST;

import FESI.Parser.*;

public
class ASTSwitchStatement extends SimpleNode {
    private static final long serialVersionUID = -1581966087028382074L;


    public ASTSwitchStatement(int id) {
        super(id);
    }

    public ASTSwitchStatement(EcmaScript p, int id) {
        super(p, id);
    }


    /** Accept the visitor. **/
    @Override
    public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=bb075a87c37c199eb3b695934cbe69d4 (do not edit this line) */
