/* Generated By:JJTree: Do not edit this line. ASTThrowStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package FESI.AST;

import FESI.Parser.*;

public class ASTThrowStatement extends SimpleNode {
    private static final long serialVersionUID = -2346319553016771996L;

    public ASTThrowStatement(int id) {
        super(id);
    }

    public ASTThrowStatement(EcmaScript p, int id) {
        super(p, id);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
/*
 * JavaCC - OriginalChecksum=7dad4d58cff72c9b6b7636f0359861fa (do not edit this
 * line)
 */
