/* Generated By:JavaCC: Do not edit this line. EcmaScriptTreeConstants.java Version 5.0 */
package FESI.AST;


public interface EcmaScriptTreeConstants
{
  public int JJTLITERAL = 0;
  public int JJTVOID = 1;
  public int JJTIDENTIFIER = 2;
  public int JJTCOMPOSITEREFERENCE = 3;
  public int JJTTHISREFERENCE = 4;
  public int JJTSUPERREFERENCE = 5;
  public int JJTFUNCTIONEXPRESSION = 6;
  public int JJTFORMALPARAMETERLIST = 7;
  public int JJTFUNCTIONCALLPARAMETERS = 8;
  public int JJTPROPERTYVALUEREFERENCE = 9;
  public int JJTPROPERTYIDENTIFIERREFERENCE = 10;
  public int JJTALLOCATIONEXPRESSION = 11;
  public int JJTARRAYLITERAL = 12;
  public int JJTELISION = 13;
  public int JJTOBJECTLITERAL = 14;
  public int JJTPROPERTYNAMEANDVALUE = 15;
  public int JJTGETACCESSOR = 16;
  public int JJTSETACCESSOR = 17;
  public int JJTOPERATOR = 18;
  public int JJTPOSTFIXEXPRESSION = 19;
  public int JJTUNARYEXPRESSION = 20;
  public int JJTBINARYEXPRESSIONSEQUENCE = 21;
  public int JJTANDEXPRESSIONSEQUENCE = 22;
  public int JJTOREXPRESSIONSEQUENCE = 23;
  public int JJTCONDITIONALEXPRESSION = 24;
  public int JJTASSIGNMENTEXPRESSION = 25;
  public int JJTEXPRESSIONLIST = 26;
  public int JJTSTATEMENT = 27;
  public int JJTSTATEMENTLIST = 28;
  public int JJTVARIABLEDECLARATION = 29;
  public int JJTIFSTATEMENT = 30;
  public int JJTDOWHILESTATEMENT = 31;
  public int JJTWHILESTATEMENT = 32;
  public int JJTFORSTATEMENT = 33;
  public int JJTEMPTYEXPRESSION = 34;
  public int JJTFORVARSTATEMENT = 35;
  public int JJTFORINSTATEMENT = 36;
  public int JJTFORVARINSTATEMENT = 37;
  public int JJTCONTINUESTATEMENT = 38;
  public int JJTBREAKSTATEMENT = 39;
  public int JJTRETURNSTATEMENT = 40;
  public int JJTWITHSTATEMENT = 41;
  public int JJTTRYSTATEMENT = 42;
  public int JJTTHROWSTATEMENT = 43;
  public int JJTCATCH = 44;
  public int JJTFINALLY = 45;
  public int JJTSWITCHSTATEMENT = 46;
  public int JJTCASECLAUSE = 47;
  public int JJTDEFAULTCLAUSE = 48;
  public int JJTFUNCTIONDECLARATION = 49;
  public int JJTPROGRAM = 50;


  public String[] jjtNodeName = {
    "Literal",
    "void",
    "Identifier",
    "CompositeReference",
    "ThisReference",
    "SuperReference",
    "FunctionExpression",
    "FormalParameterList",
    "FunctionCallParameters",
    "PropertyValueReference",
    "PropertyIdentifierReference",
    "AllocationExpression",
    "ArrayLiteral",
    "Elision",
    "ObjectLiteral",
    "PropertyNameAndValue",
    "GetAccessor",
    "SetAccessor",
    "Operator",
    "PostfixExpression",
    "UnaryExpression",
    "BinaryExpressionSequence",
    "AndExpressionSequence",
    "OrExpressionSequence",
    "ConditionalExpression",
    "AssignmentExpression",
    "ExpressionList",
    "Statement",
    "StatementList",
    "VariableDeclaration",
    "IfStatement",
    "DoWhileStatement",
    "WhileStatement",
    "ForStatement",
    "EmptyExpression",
    "ForVarStatement",
    "ForInStatement",
    "ForVarInStatement",
    "ContinueStatement",
    "BreakStatement",
    "ReturnStatement",
    "WithStatement",
    "TryStatement",
    "ThrowStatement",
    "Catch",
    "Finally",
    "SwitchStatement",
    "CaseClause",
    "DefaultClause",
    "FunctionDeclaration",
    "Program",
  };
}
/* JavaCC - OriginalChecksum=11920db6c9c6da2c5d5ab7c6cf1e405f (do not edit this line) */
