/* Generated By:JavaCC: Do not edit this line. EcmaScriptTreeConstants.java Version 5.0 */
package FESI.AST;


public interface EcmaScriptTreeConstants
{
  public int JJTLITERAL = 0;
  public int JJTVOID = 1;
  public int JJTIDENTIFIER = 2;
  public int JJTTHISREFERENCE = 3;
  public int JJTSUPERREFERENCE = 4;
  public int JJTCOMPOSITEREFERENCE = 5;
  public int JJTFUNCTIONCALLPARAMETERS = 6;
  public int JJTPROPERTYVALUEREFERENCE = 7;
  public int JJTPROPERTYIDENTIFIERREFERENCE = 8;
  public int JJTALLOCATIONEXPRESSION = 9;
  public int JJTOBJECTLITERAL = 10;
  public int JJTPROPERTYNAMEANDVALUE = 11;
  public int JJTOPERATOR = 12;
  public int JJTPOSTFIXEXPRESSION = 13;
  public int JJTUNARYEXPRESSION = 14;
  public int JJTBINARYEXPRESSIONSEQUENCE = 15;
  public int JJTANDEXPRESSIONSEQUENCE = 16;
  public int JJTOREXPRESSIONSEQUENCE = 17;
  public int JJTCONDITIONALEXPRESSION = 18;
  public int JJTASSIGNMENTEXPRESSION = 19;
  public int JJTEXPRESSIONLIST = 20;
  public int JJTSTATEMENT = 21;
  public int JJTSTATEMENTLIST = 22;
  public int JJTVARIABLEDECLARATION = 23;
  public int JJTIFSTATEMENT = 24;
  public int JJTWHILESTATEMENT = 25;
  public int JJTFORSTATEMENT = 26;
  public int JJTEMPTYEXPRESSION = 27;
  public int JJTFORVARSTATEMENT = 28;
  public int JJTFORINSTATEMENT = 29;
  public int JJTFORVARINSTATEMENT = 30;
  public int JJTCONTINUESTATEMENT = 31;
  public int JJTBREAKSTATEMENT = 32;
  public int JJTRETURNSTATEMENT = 33;
  public int JJTWITHSTATEMENT = 34;
  public int JJTFUNCTIONDECLARATION = 35;
  public int JJTFORMALPARAMETERLIST = 36;
  public int JJTPROGRAM = 37;


  public String[] jjtNodeName = {
    "Literal",
    "void",
    "Identifier",
    "ThisReference",
    "SuperReference",
    "CompositeReference",
    "FunctionCallParameters",
    "PropertyValueReference",
    "PropertyIdentifierReference",
    "AllocationExpression",
    "ObjectLiteral",
    "PropertyNameAndValue",
    "Operator",
    "PostfixExpression",
    "UnaryExpression",
    "BinaryExpressionSequence",
    "AndExpressionSequence",
    "OrExpressionSequence",
    "ConditionalExpression",
    "AssignmentExpression",
    "ExpressionList",
    "Statement",
    "StatementList",
    "VariableDeclaration",
    "IfStatement",
    "WhileStatement",
    "ForStatement",
    "EmptyExpression",
    "ForVarStatement",
    "ForInStatement",
    "ForVarInStatement",
    "ContinueStatement",
    "BreakStatement",
    "ReturnStatement",
    "WithStatement",
    "FunctionDeclaration",
    "FormalParameterList",
    "Program",
  };
}
/* JavaCC - OriginalChecksum=ab7b2c4e53ea85951a660fd034bcd21b (do not edit this line) */
